version: '3'
services:
  database:
    image: postgres:14.5-alpine3.16
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    ports:
      - '5432:5432'
    volumes:
      - todo-db:/db

volumes:
  todo-db:
